"""widen source_series.external_unit

Revision ID: 937030256f0d
Revises: 1200d23f78f6
Create Date: 2026-09-08 11:44:31.537133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937030256f0d'
down_revision: Union[str, Sequence[str], None] = '1200d23f78f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_countries_iso2', 'countries', ['iso2'])
    op.alter_column('source_series', 'external_unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_series', 'external_unit',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint('uq_countries_iso2', 'countries', type_='unique')
    # ### end Alembic commands ###
