"""add data foundation

Revision ID: d46a4baae782
Revises: 2bf93faf72ce
Create Date: 2026-09-07 20:50:02.891399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46a4baae782'
down_revision: Union[str, Sequence[str], None] = '2bf93faf72ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('update_frequency', sa.String(length=50), nullable=True),
    sa.Column('rate_limit_notes', sa.Text(), nullable=True),
    sa.Column('documentation_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_key'), 'data_sources', ['key'], unique=True)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('strength_direction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_code'), 'indicators', ['code'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_revised', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=False),
    sa.Column('external_name', sa.String(length=120), nullable=True),
    sa.Column('external_unit', sa.String(length=20), nullable=True),
    sa.Column('country_scope', sa.String(length=50), nullable=True),
    sa.Column('transform_notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_series_data_source_id'), 'source_series', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_series_indicator_id'), 'source_series', ['indicator_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('source_series_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vintage_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_observation_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['source_series_id'], ['source_series.id'], ),
    sa.ForeignKeyConstraint(['supersedes_observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_country_id'), 'observations', ['country_id'], unique=False)
    op.create_index(op.f('ix_observations_data_source_id'), 'observations', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_observations_indicator_id'), 'observations', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_observations_observation_date'), 'observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_observations_period_start'), 'observations', ['period_start'], unique=False)
    op.create_index(op.f('ix_observations_release_date'), 'observations', ['release_date'], unique=False)
    op.create_index(op.f('ix_observations_retrieved_at'), 'observations', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_observations_source_series_id'), 'observations', ['source_series_id'], unique=False)
    op.create_table('indicator_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prior_observation_id', sa.Integer(), nullable=True),
    sa.Column('new_observation_id', sa.Integer(), nullable=False),
    sa.Column('revision_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['new_observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['prior_observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_revisions')
    op.drop_index(op.f('ix_observations_source_series_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_retrieved_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_release_date'), table_name='observations')
    op.drop_index(op.f('ix_observations_period_start'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_date'), table_name='observations')
    op.drop_index(op.f('ix_observations_indicator_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_data_source_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_country_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_source_series_indicator_id'), table_name='source_series')
    op.drop_index(op.f('ix_source_series_data_source_id'), table_name='source_series')
    op.drop_table('source_series')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_indicators_code'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_data_sources_key'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
